function h1 = energy_io()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.


load energy_io.mat


h1 = figure(...
'Color',[1 1 1],...
'Colormap',get(0,'defaultfigureColormap'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',get(0,'defaultfigurePosition'),...
'DefaultaxesColorOrder',mat{1});

appdata = [];
appdata.PlotColorIndex = mat{2};
appdata.PlotLineStyleIndex = mat{3};
appdata.graphicsPlotyyPeer = mat{4};
appdata.graphicsPlotyyLinkProp = mat{5};
appdata.graphicsPlotyyPositionListener = mat{6};
appdata.PlotHoldStyle = mat{7};

h2 = axes(...
'Parent',h1,...
'Box','on',...
'CameraPosition',[25 0.2 17.3205080756888],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'NextPlot','add',...
'XColor',get(0,'defaultaxesXColor'),...
'XLim',[0 50],...
'XLimMode','manual',...
'YColor',[0 0 1],...
'YLim',[0 0.4],...
'YLimMode','manual',...
'YTick',[0 0.2 0.4],...
'YTickMode','manual',...
'ZColor',get(0,'defaultaxesZColor'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h3 = get(h2,'xlabel');

set(h3,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[24.9423963133641 -0.0274853801169591 1.00010919874411],...
'Rotation',0,...
'String','Confining Pressure (MPa)',...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h4 = get(h2,'ylabel');

set(h4,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 1],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-3.28341013824885 0.198245614035088 1.00010919874411],...
'Rotation',90,...
'String','Fracture Energy (MJ) / Input Energy (MJ)',...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.legend_texthandle = mat{8};
appdata.legend_linetokenhandle = mat{9};
appdata.legend_linemarkertokenhandle = mat{10};

h5 = graph2d.lineseries(...
'Parent',h2,...
'DisplayName','Lac Du Bonnet Granite Fracture Energy/ Input Energy',...
'Color',[0 0 1],...
'LineStyle',':',...
'LineWidth',3,...
'Marker','square',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0 1],...
'XData',mat{11},...
'YData',mat{12},...
'XDataJitter',0,...
'XDataMode','manual',...
'ObeyXDataMode','auto',...
'XDataSource',blanks(0),...
'YDataSource',blanks(0),...
'ZDataSource',blanks(0),...
'CodeGenColorMode','auto',...
'CodeGenLineStyleMode','manual',...
'CodeGenMarkerMode','manual',...
'SwitchProps',{  'LineWidth'; 'LineStyle'; 'Color'; 'MarkerEdgeColor'; 'MarkerFaceColor'; 'Marker'; 'MarkerSize'; 'Visible'; 'XDataSource'; 'YDataSource'; 'ZDataSource'; 'DisplayName' },...
'OldSwitchProps',[],...
'OldSwitchVals',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h6 = text(...
'Parent',h2,...
'Color',get(0,'defaulttextColor'),...
'DeleteFcn','try;delete(get(gcbo,''userdata''));end',...
'HandleVisibility','off',...
'Tag','PlotyyDeleteProxy',...
'UserData',[],...
'Visible','off');

appdata = [];
appdata.legend_texthandle = mat{13};
appdata.legend_linetokenhandle = mat{14};
appdata.legend_linemarkertokenhandle = mat{15};

h7 = graph2d.lineseries(...
'Parent',h2,...
'DisplayName','Berea Sandstone Fracture Energy/ Input Energy',...
'Color',[0 0 1],...
'LineWidth',3,...
'Marker','o',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0 1],...
'XData',mat{16},...
'YData',mat{17},...
'XDataJitter',0,...
'XDataMode','manual',...
'ObeyXDataMode','auto',...
'XDataSource',blanks(0),...
'YDataSource',blanks(0),...
'ZDataSource',blanks(0),...
'CodeGenColorMode','auto',...
'CodeGenLineStyleMode','auto',...
'CodeGenMarkerMode','manual',...
'SwitchProps',{  'LineWidth'; 'LineStyle'; 'Color'; 'MarkerEdgeColor'; 'MarkerFaceColor'; 'Marker'; 'MarkerSize'; 'Visible'; 'XDataSource'; 'YDataSource'; 'ZDataSource'; 'DisplayName' },...
'OldSwitchProps',[],...
'OldSwitchVals',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h8 = text(...
'Parent',h2,...
'Color',get(0,'defaulttextColor'),...
'DeleteFcn','try;delete(get(gcbo,''userdata''));end',...
'HandleVisibility','off',...
'Tag','PlotyyDeleteProxy',...
'UserData',[],...
'Visible','off');

appdata = [];
appdata.PlotColorIndex = mat{18};
appdata.PlotLineStyleIndex = mat{19};
appdata.graphicsPlotyyPeer = mat{20};

h9 = axes(...
'Parent',h1,...
'CameraPosition',[25 15 17.3205080756888],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color','none',...
'ColorOrder',mat{21},...
'XColor',get(0,'defaultaxesXColor'),...
'XLim',[0 50],...
'XLimMode','manual',...
'YColor',[0 0.5 0],...
'YAxisLocation','right',...
'YLim',[0 30],...
'YLimMode','manual',...
'YTick',[0 10 20 30],...
'YTickMode','manual',...
'ZColor',get(0,'defaultaxesZColor'),...
'HitTest','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h10 = get(h9,'ylabel');

set(h10,...
'Parent',h9,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0.5 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[52.5921658986175 14.8684210526316 1.00010919874411],...
'Rotation',90,...
'String','Input Energy (MJ)',...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.legend_texthandle = mat{22};
appdata.legend_linetokenhandle = mat{23};
appdata.legend_linemarkertokenhandle = mat{24};

h11 = graph2d.lineseries(...
'Parent',h9,...
'DisplayName','Lac Du Bonnet Granite Input Energy',...
'Color',[0 0.5 0],...
'LineStyle',':',...
'LineWidth',3,...
'Marker','square',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0.5 0],...
'XData',mat{25},...
'YData',mat{26},...
'XDataJitter',0,...
'XDataMode','manual',...
'ObeyXDataMode','auto',...
'XDataSource',blanks(0),...
'YDataSource',blanks(0),...
'ZDataSource',blanks(0),...
'CodeGenColorMode','auto',...
'CodeGenLineStyleMode','manual',...
'CodeGenMarkerMode','manual',...
'SwitchProps',{  'LineWidth'; 'LineStyle'; 'Color'; 'MarkerEdgeColor'; 'MarkerFaceColor'; 'Marker'; 'MarkerSize'; 'Visible'; 'XDataSource'; 'YDataSource'; 'ZDataSource'; 'DisplayName' },...
'OldSwitchProps',[],...
'OldSwitchVals',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h12 = text(...
'Parent',h9,...
'Color',get(0,'defaulttextColor'),...
'DeleteFcn','try;delete(get(gcbo,''userdata''));end',...
'HandleVisibility','off',...
'Tag','PlotyyDeleteProxy',...
'UserData',[],...
'Visible','off');

appdata = [];
appdata.PlotColorIndex = mat{27};
appdata.PlotLineStyleIndex = mat{28};
appdata.graphicsPlotyyPeer = mat{29};
appdata.LegendColorbarText = mat{30};
appdata.LegendColorbarInnerList = mat{31};
appdata.LegendColorbarOuterList = mat{32};
appdata.inLayout = mat{33};
appdata.LegendComputePosCache = mat{34};
appdata.LegendPeerHandle = mat{35};

h13 = axes(...
'Parent',h1,...
'CameraPosition',[25 20 17.3205080756888],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color','none',...
'ColorOrder',mat{36},...
'XColor',get(0,'defaultaxesXColor'),...
'XLim',[0 50],...
'XLimMode','manual',...
'YColor',[0 0.5 0],...
'YAxisLocation','right',...
'YLim',[0 40],...
'YLimMode','manual',...
'YTick',[],...
'YTickLabel',blanks(0),...
'YTickLabelMode','manual',...
'YTickMode','manual',...
'ZColor',get(0,'defaultaxesZColor'),...
'HitTest','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h14 = get(h13,'title');

set(h14,...
'Parent',h13,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[24.9423963133641 40.7602339181286 1.00010919874411],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h15 = get(h13,'xlabel');

set(h15,...
'Parent',h13,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[24.9423963133641 -2.74853801169591 1.00010919874411],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h16 = get(h13,'ylabel');

set(h16,...
'Parent',h13,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0.5 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[50.7488479262673 19.8245614035088 1.00010919874411],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h17 = get(h13,'zlabel');

set(h17,...
'Parent',h13,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',[],...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-8.46774193548387 43.5672514619883 1.00010919874411],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.legend_texthandle = mat{37};
appdata.legend_linetokenhandle = mat{38};
appdata.legend_linemarkertokenhandle = mat{39};

h18 = graph2d.lineseries(...
'Parent',h13,...
'DisplayName','Berea Sandstone Input Energy',...
'Color',[0 0.5 0],...
'LineWidth',3,...
'Marker','o',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0.5 0],...
'XData',mat{40},...
'YData',mat{41},...
'XDataJitter',0,...
'XDataMode','manual',...
'ObeyXDataMode','auto',...
'XDataSource',blanks(0),...
'YDataSource',blanks(0),...
'ZDataSource',blanks(0),...
'CodeGenColorMode','auto',...
'CodeGenLineStyleMode','auto',...
'CodeGenMarkerMode','manual',...
'SwitchProps',{  'LineWidth'; 'LineStyle'; 'Color'; 'MarkerEdgeColor'; 'MarkerFaceColor'; 'Marker'; 'MarkerSize'; 'Visible'; 'XDataSource'; 'YDataSource'; 'ZDataSource'; 'DisplayName' },...
'OldSwitchProps',[],...
'OldSwitchVals',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h19 = text(...
'Parent',h13,...
'Color',get(0,'defaulttextColor'),...
'DeleteFcn','try;delete(get(gcbo,''userdata''));end',...
'HandleVisibility','off',...
'Tag','PlotyyDeleteProxy',...
'UserData',[],...
'Visible','off');

h20 = text(...
'Parent',h13,...
'Color',get(0,'defaulttextColor'),...
'HandleVisibility','off',...
'Tag','LegendDeleteProxy',...
'Visible','off');

h21 = text(...
'Parent',h13,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'HorizontalAlignment','center',...
'String',' ',...
'DeleteFcn','legendcolorbarlayout(get(gcbo,''Parent''),''remove'')',...
'HandleVisibility','off',...
'HitTest','off',...
'Tag','LegendColorbarLayout');

h22 = text(...
'Parent',h13,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'HorizontalAlignment','center',...
'Position',[1 1 0],...
'String',' ',...
'HandleVisibility','off',...
'HitTest','off',...
'Tag','LegendColorbarLayout');

appdata = [];
appdata.LegendTempText = mat{42};
appdata.MWBYPASS_title = mat{43};
appdata.MWBYPASS_xlabel = mat{44};
appdata.MWBYPASS_ylabel = mat{45};
appdata.MWBYPASS_zlabel = mat{46};
appdata.NonDataObject = mat{47};
appdata.PostDeserializeFcn = mat{48};
appdata.LegendOldSize = mat{49};

h23 = scribe.legend(...
'Parent',h1,...
'Position',[0.143154761904762 0.727380952380952 0.616071428571428 0.179365079365079],...
'Box','on',...
'CameraPosition',[0.5 0.5 17.3205080756888],...
'CameraPositionMode','auto',...
'CLim',[0 1],...
'CLimMode','manual',...
'Color',[0.8 0.8 0.8],...
'DrawMode','fast',...
'FontSize',[],...
'LooseInset',[0 0 0 0],...
'NextPlot','add',...
'XColor',[0 0 0],...
'XLim',[0 1],...
'XLimMode','manual',...
'XTick',-1,...
'XTickLabel',blanks(0),...
'XTickLabelMode','manual',...
'XTickMode','manual',...
'YColor',[0 0 0],...
'YLim',[0 1],...
'YLimMode','manual',...
'YTick',-1,...
'YTickLabel',blanks(0),...
'YTickLabelMode','manual',...
'YTickMode','manual',...
'ZColor',[0 0 0],...
'ButtonDownFcn',mat{50},...
'Interruptible','off',...
'Tag','legend',...
'UserData',struct(...
    'PlotHandle', [], ...
    'legendpos', 2, ...
    'LegendPosition', [0.143154761904762 0.727380952380952 0.616071428571428 0.179365079365079], ...
    'LabelHandles', [], ...
    'handles', [], ...
    'lstrings', { {  'Berea Sandstone Input Energy'; 'Berea Sandstone Fracture Energy/ Input Energy'; 'Lac Du Bonnet Granite Input Energy'; 'Lac Du Bonnet Granite Fracture Energy/ Input Energy' } }, ...
    'LegendHandle', []),...
'PlotChildListen','off',...
'Image',[],...
'Location','NorthWest',...
'Orientation','vertical',...
'ItemTextLocation','left',...
'ItemTokenSize',[30 18],...
'StyleLegend','on',...
'EdgeColor',[0 0 0],...
'ObserveText','on',...
'TextColor',[0 0 0],...
'Interpreter','tex',...
'String',{  'Berea Sandstone Input Energy' 'Berea Sandstone Fracture Energy/ Input Energy' 'Lac Du Bonnet Granite Input Energy' 'Lac Du Bonnet Granite Fracture Energy/ Input Energy' },...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h24 = text(...
'Parent',h23,...
'Units','points',...
'Color',get(0,'defaulttextColor'),...
'FontSize',[],...
'Margin',0.01,...
'String','Lac Du Bonnet Granite Fracture Energy/ Input Energy',...
'HandleVisibility','off',...
'Tag','temphackytext',...
'Visible','off');

appdata = [];
appdata.Listeners = mat{51};

h25 = text(...
'Parent',h23,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'FontSize',[],...
'Position',[0.150724637681159 0.851769911504425 0],...
'String','Berea Sandstone Input Energy',...
'ButtonDownFcn',mat{52},...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h26 = line(...
'Parent',h23,...
'Color',[0 0.5 0],...
'LineWidth',3,...
'XData',[0.0231884057971014 0.139130434782609],...
'YData',[0.851769911504425 0.851769911504425],...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'Tag','Berea Sandstone Input Energy');

h27 = line(...
'Parent',h23,...
'Color',[0 0.5 0],...
'LineStyle','none',...
'LineWidth',3,...
'Marker','o',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0.5 0],...
'XData',0.0811594202898551,...
'YData',0.851769911504425,...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off');

appdata = [];
appdata.Listeners = mat{53};

h28 = text(...
'Parent',h23,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'FontSize',[],...
'Position',[0.150724637681159 0.617256637168142 0],...
'String','Berea Sandstone Fracture Energy/ Input Energy',...
'ButtonDownFcn',mat{54},...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h29 = line(...
'Parent',h23,...
'Color',[0 0 1],...
'LineWidth',3,...
'XData',[0.0231884057971014 0.139130434782609],...
'YData',[0.617256637168142 0.617256637168142],...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'Tag','Berea Sandstone Fracture Energy/ Input Energy');

h30 = line(...
'Parent',h23,...
'Color',[0 0 1],...
'LineStyle','none',...
'LineWidth',3,...
'Marker','o',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0 1],...
'XData',0.0811594202898551,...
'YData',0.617256637168142,...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off');

appdata = [];
appdata.Listeners = mat{55};

h31 = text(...
'Parent',h23,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'FontSize',[],...
'Position',[0.150724637681159 0.382743362831858 0],...
'String','Lac Du Bonnet Granite Input Energy',...
'ButtonDownFcn',mat{56},...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h32 = line(...
'Parent',h23,...
'Color',[0 0.5 0],...
'LineStyle',':',...
'LineWidth',3,...
'XData',[0.0231884057971014 0.139130434782609],...
'YData',[0.382743362831858 0.382743362831858],...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'Tag','Lac Du Bonnet Granite Input Energy');

h33 = line(...
'Parent',h23,...
'Color',[0 0.5 0],...
'LineStyle','none',...
'LineWidth',3,...
'Marker','square',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0.5 0],...
'XData',0.0811594202898551,...
'YData',0.382743362831858,...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off');

appdata = [];
appdata.Listeners = mat{57};

h34 = text(...
'Parent',h23,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'FontSize',[],...
'Position',[0.150724637681159 0.148230088495575 0],...
'String','Lac Du Bonnet Granite Fracture Energy/ Input Energy',...
'ButtonDownFcn',mat{58},...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h35 = line(...
'Parent',h23,...
'Color',[0 0 1],...
'LineStyle',':',...
'LineWidth',3,...
'XData',[0.0231884057971014 0.139130434782609],...
'YData',[0.148230088495575 0.148230088495575],...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'Tag','Lac Du Bonnet Granite Fracture Energy/ Input Energy');

h36 = line(...
'Parent',h23,...
'Color',[0 0 1],...
'LineStyle','none',...
'LineWidth',3,...
'Marker','square',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0 0 1],...
'XData',0.0811594202898551,...
'YData',0.148230088495575,...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off');

appdata = [];
appdata.CallbackObject = mat{59};

h37 = uicontextmenu(...
'Parent',h1,...
'HandleVisibility','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h38 = uimenu(...
'Parent',h37,...
'Callback',mat{60},...
'Label','Refresh',...
'HandleVisibility','off',...
'Tag','scribe:legend:refresh');

h39 = uimenu(...
'Parent',h37,...
'Callback',mat{61},...
'Label','Delete',...
'HandleVisibility','off',...
'Tag','scribe:legend:delete');

h40 = uimenu(...
'Parent',h37,...
'Callback',mat{62},...
'Label','Color ...',...
'Separator','on',...
'HandleVisibility','off',...
'Tag','scribe:legend:color');

h41 = uimenu(...
'Parent',h37,...
'Callback',mat{63},...
'Label','Edge Color ...',...
'HandleVisibility','off',...
'Tag','scribe:legend:edgecolor');

h42 = uimenu(...
'Parent',h37,...
'Callback',mat{64},...
'Label','Line Width',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth');

h43 = uimenu(...
'Parent',h42,...
'Callback',mat{65},...
'Label','0.5',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:0.5');

h44 = uimenu(...
'Parent',h42,...
'Callback',mat{66},...
'Label','1.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:1.0');

h45 = uimenu(...
'Parent',h42,...
'Callback',mat{67},...
'Label','2.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:2.0');

h46 = uimenu(...
'Parent',h42,...
'Callback',mat{68},...
'Label','3.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:3.0');

h47 = uimenu(...
'Parent',h42,...
'Callback',mat{69},...
'Label','4.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:4.0');

h48 = uimenu(...
'Parent',h42,...
'Callback',mat{70},...
'Label','5.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:5.0');

h49 = uimenu(...
'Parent',h42,...
'Callback',mat{71},...
'Label','6.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:6.0');

h50 = uimenu(...
'Parent',h42,...
'Callback',mat{72},...
'Label','7.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:7.0');

h51 = uimenu(...
'Parent',h42,...
'Callback',mat{73},...
'Label','8.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:8.0');

h52 = uimenu(...
'Parent',h42,...
'Callback',mat{74},...
'Label','9.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:9.0');

h53 = uimenu(...
'Parent',h42,...
'Callback',mat{75},...
'Label','10.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:10.0');

h54 = uimenu(...
'Parent',h42,...
'Callback',mat{76},...
'Label','11.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:11.0');

h55 = uimenu(...
'Parent',h42,...
'Callback',mat{77},...
'Label','12.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:12.0');

h56 = uimenu(...
'Parent',h37,...
'Callback',mat{78},...
'Label','Font ...',...
'HandleVisibility','off',...
'Tag','scribe:legend:font');

h57 = uimenu(...
'Parent',h37,...
'Callback',mat{79},...
'Label','Interpreter',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter');

h58 = uimenu(...
'Parent',h57,...
'Callback',mat{80},...
'Label','latex',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter:latex');

h59 = uimenu(...
'Parent',h57,...
'Callback',mat{81},...
'Label','tex',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter:tex');

h60 = uimenu(...
'Parent',h57,...
'Callback',mat{82},...
'Label','none',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter:none');

h61 = uimenu(...
'Parent',h37,...
'Callback',mat{83},...
'Label','Location',...
'HandleVisibility','off',...
'Tag','scribe:legend:location');

h62 = uimenu(...
'Parent',h61,...
'Callback',mat{84},...
'Label','Best',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:best');

h63 = uimenu(...
'Parent',h61,...
'Callback',mat{85},...
'Label','Inside North East',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northeast');

h64 = uimenu(...
'Parent',h61,...
'Callback',mat{86},...
'Label','Outside North East',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northeastoutside');

h65 = uimenu(...
'Parent',h61,...
'Callback',mat{87},...
'Label','Inside South East',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:southeast');

h66 = uimenu(...
'Parent',h61,...
'Callback',mat{88},...
'Label','Inside North West',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northwest');

h67 = uimenu(...
'Parent',h61,...
'Callback',mat{89},...
'Label','Outside North West',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northwestoutside');

h68 = uimenu(...
'Parent',h61,...
'Callback',mat{90},...
'Label','Inside South West',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:southwest');

h69 = uimenu(...
'Parent',h37,...
'Callback',mat{91},...
'Label','Orientation',...
'HandleVisibility','off',...
'Tag','scribe:legend:orientation');

h70 = uimenu(...
'Parent',h69,...
'Callback',mat{92},...
'Label','vertical',...
'HandleVisibility','off',...
'Tag','scribe:legend:orientation:vertical');

h71 = uimenu(...
'Parent',h69,...
'Callback',mat{93},...
'Label','horizontal',...
'HandleVisibility','off',...
'Tag','scribe:legend:orientation:horizontal');

h72 = uimenu(...
'Parent',h37,...
'Callback',mat{94},...
'Label','Show Property Editor',...
'Separator','on',...
'HandleVisibility','off',...
'Tag','scribe:legend:propedit');

h73 = uimenu(...
'Parent',h37,...
'Callback',mat{95},...
'Label','Show M-Code',...
'Separator','on',...
'HandleVisibility','off',...
'Tag','scribe:legend:mcode');

handles = [ h23 ];
set(handles, 'uicontextmenu', h37);



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end
