function h1 = number_mf()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
% 
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.


load number_mf.mat


h1 = figure(...
'Color',[],...
'Colormap',get(0,'defaultfigureColormap'),...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'Position',get(0,'defaultfigurePosition'));

appdata = [];
appdata.PlotColorIndex = mat{1};
appdata.PlotLineStyleIndex = mat{2};
appdata.PlotHoldStyle = mat{3};
appdata.LegendColorbarText = mat{4};
appdata.LegendColorbarInnerList = mat{5};
appdata.LegendColorbarOuterList = mat{6};
appdata.inLayout = mat{7};
appdata.LegendComputePosCache = mat{8};
appdata.LegendPeerHandle = mat{9};

h2 = axes(...
'Parent',h1,...
'Box','on',...
'CameraPosition',[25 4250 17.3205080756888],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'NextPlot','add',...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'YLim',[2000 6500],...
'YLimMode','manual',...
'ZColor',get(0,'defaultaxesZColor'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h3 = get(h2,'title');

set(h3,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[24.9423963133641 6585.52631578947 1.0001091987441],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h4 = get(h2,'xlabel');

set(h4,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[24.9423963133641 1690.78947368421 1.0001091987441],...
'Rotation',0,...
'String','Confining Pressure (MPa)',...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h5 = get(h2,'ylabel');

set(h5,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-4.43548387096774 4230.26315789474 1.0001091987441],...
'Rotation',90,...
'String','Number of Microfractures',...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h6 = get(h2,'zlabel');

set(h6,...
'Parent',h2,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-8.46774193548387 6901.31578947368 1.0001091987441],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.legend_texthandle = mat{10};
appdata.legend_linetokenhandle = mat{11};
appdata.legend_linemarkertokenhandle = mat{12};

h7 = graph2d.lineseries(...
'Parent',h2,...
'DisplayName','Berea Sandstone',...
'Color',[0 0 0],...
'LineStyle',':',...
'LineWidth',2,...
'Marker','o',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0.5 0.5 0.5],...
'XData',mat{13},...
'YData',mat{14},...
'XDataJitter',0,...
'XDataMode','manual',...
'ObeyXDataMode','auto',...
'XDataSource',blanks(0),...
'YDataSource',blanks(0),...
'ZDataSource',blanks(0),...
'CodeGenColorMode','manual',...
'CodeGenLineStyleMode','manual',...
'CodeGenMarkerMode','manual',...
'SwitchProps',{  'LineWidth'; 'LineStyle'; 'Color'; 'MarkerEdgeColor'; 'MarkerFaceColor'; 'Marker'; 'MarkerSize'; 'Visible'; 'XDataSource'; 'YDataSource'; 'ZDataSource'; 'DisplayName' },...
'OldSwitchProps',[],...
'OldSwitchVals',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.legend_texthandle = mat{15};
appdata.legend_linetokenhandle = mat{16};
appdata.legend_linemarkertokenhandle = mat{17};

h8 = graph2d.lineseries(...
'Parent',h2,...
'DisplayName','Lac Du Bonnet Granite',...
'Color',[0 0 0],...
'LineWidth',2,...
'Marker','square',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0.9 0.9 0.9],...
'XData',mat{18},...
'YData',mat{19},...
'XDataJitter',0,...
'XDataMode','manual',...
'ObeyXDataMode','auto',...
'XDataSource',blanks(0),...
'YDataSource',blanks(0),...
'ZDataSource',blanks(0),...
'CodeGenColorMode','manual',...
'CodeGenLineStyleMode','auto',...
'CodeGenMarkerMode','manual',...
'SwitchProps',{  'LineWidth'; 'LineStyle'; 'Color'; 'MarkerEdgeColor'; 'MarkerFaceColor'; 'Marker'; 'MarkerSize'; 'Visible'; 'XDataSource'; 'YDataSource'; 'ZDataSource'; 'DisplayName' },...
'OldSwitchProps',[],...
'OldSwitchVals',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h9 = text(...
'Parent',h2,...
'Color',get(0,'defaulttextColor'),...
'HandleVisibility','off',...
'Tag','LegendDeleteProxy',...
'Visible','off');

h10 = text(...
'Parent',h2,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'HorizontalAlignment','center',...
'String',' ',...
'DeleteFcn','legendcolorbarlayout(get(gcbo,''Parent''),''remove'')',...
'HandleVisibility','off',...
'HitTest','off',...
'Tag','LegendColorbarLayout');

h11 = text(...
'Parent',h2,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'HorizontalAlignment','center',...
'Position',[1 1 0],...
'String',' ',...
'HandleVisibility','off',...
'HitTest','off',...
'Tag','LegendColorbarLayout');

appdata = [];
appdata.LegendTempText = mat{20};
appdata.MWBYPASS_title = mat{21};
appdata.MWBYPASS_xlabel = mat{22};
appdata.MWBYPASS_ylabel = mat{23};
appdata.MWBYPASS_zlabel = mat{24};
appdata.NonDataObject = mat{25};
appdata.PostDeserializeFcn = mat{26};
appdata.LegendOldSize = mat{27};

h12 = scribe.legend(...
'Parent',h1,...
'Position',[0.571130952380952 0.121825396825397 0.325 0.0952380952380952],...
'Box','on',...
'CameraPosition',[0.5 0.5 17.3205080756888],...
'CameraPositionMode','auto',...
'CLim',[0 1],...
'CLimMode','manual',...
'Color',[],...
'ColorOrder',mat{28},...
'DrawMode','fast',...
'FontSize',9,...
'LooseInset',[0 0 0 0],...
'NextPlot','add',...
'XColor',[0 0 0],...
'XLim',[0 1],...
'XLimMode','manual',...
'XTick',-1,...
'XTickLabel',blanks(0),...
'XTickLabelMode','manual',...
'XTickMode','manual',...
'YColor',[0 0 0],...
'YLim',[0 1],...
'YLimMode','manual',...
'YTick',-1,...
'YTickLabel',blanks(0),...
'YTickLabelMode','manual',...
'YTickMode','manual',...
'ZColor',[0 0 0],...
'ButtonDownFcn',mat{29},...
'Interruptible','off',...
'Tag','legend',...
'UserData',struct(...
    'PlotHandle', [], ...
    'legendpos', 4, ...
    'LegendPosition', [0.571130952380952 0.121825396825397 0.325 0.0952380952380952], ...
    'LabelHandles', [], ...
    'handles', [], ...
    'lstrings', { {  'Berea Sandstone'; 'Lac Du Bonnet Granite' } }, ...
    'LegendHandle', []),...
'PlotChildListen','off',...
'Image',[],...
'Location','SouthEast',...
'Orientation','vertical',...
'ItemTextLocation','left',...
'ItemTokenSize',[30 18],...
'StyleLegend','on',...
'EdgeColor',[0 0 0],...
'ObserveText','on',...
'TextColor',[0 0 0],...
'Interpreter','tex',...
'String',{  'Berea Sandstone' 'Lac Du Bonnet Granite' },...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h13 = text(...
'Parent',h12,...
'Units','points',...
'Color',get(0,'defaulttextColor'),...
'FontSize',9,...
'Margin',0.01,...
'String','Lac Du Bonnet Granite',...
'HandleVisibility','off',...
'Tag','temphackytext',...
'Visible','off');

appdata = [];
appdata.Listeners = mat{30};

h14 = text(...
'Parent',h12,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'FontSize',9,...
'Position',[0.285714285714286 0.720833333333333 0],...
'String','Berea Sandstone',...
'ButtonDownFcn',mat{31},...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h15 = line(...
'Parent',h12,...
'Color',get(0,'defaultlineColor'),...
'LineStyle',':',...
'LineWidth',2,...
'XData',[0.043956043956044 0.263736263736264],...
'YData',[0.720833333333333 0.720833333333333],...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'Tag','Berea Sandstone');

h16 = line(...
'Parent',h12,...
'Color',get(0,'defaultlineColor'),...
'LineStyle','none',...
'LineWidth',2,...
'Marker','o',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0.5 0.5 0.5],...
'XData',0.153846153846154,...
'YData',0.720833333333333,...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off');

appdata = [];
appdata.Listeners = mat{32};

h17 = text(...
'Parent',h12,...
'Units','normalized',...
'Color',get(0,'defaulttextColor'),...
'FontSize',9,...
'Position',[0.285714285714286 0.279166666666667 0],...
'String','Lac Du Bonnet Granite',...
'ButtonDownFcn',mat{33},...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h18 = line(...
'Parent',h12,...
'Color',get(0,'defaultlineColor'),...
'LineWidth',2,...
'XData',[0.043956043956044 0.263736263736264],...
'YData',[0.279166666666667 0.279166666666667],...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off',...
'Tag','Lac Du Bonnet Granite');

h19 = line(...
'Parent',h12,...
'Color',get(0,'defaultlineColor'),...
'LineStyle','none',...
'LineWidth',2,...
'Marker','square',...
'MarkerEdgeColor',[0 0 0],...
'MarkerFaceColor',[0.9 0.9 0.9],...
'XData',0.153846153846154,...
'YData',0.279166666666667,...
'HitTest','off',...
'Interruptible','off',...
'SelectionHighlight','off');

appdata = [];
appdata.CallbackObject = mat{34};

h20 = uicontextmenu(...
'Parent',h1,...
'HandleVisibility','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

h21 = uimenu(...
'Parent',h20,...
'Callback',mat{35},...
'Label','Refresh',...
'HandleVisibility','off',...
'Tag','scribe:legend:refresh');

h22 = uimenu(...
'Parent',h20,...
'Callback',mat{36},...
'Label','Delete',...
'HandleVisibility','off',...
'Tag','scribe:legend:delete');

h23 = uimenu(...
'Parent',h20,...
'Callback',mat{37},...
'Label','Color ...',...
'Separator','on',...
'HandleVisibility','off',...
'Tag','scribe:legend:color');

h24 = uimenu(...
'Parent',h20,...
'Callback',mat{38},...
'Label','Edge Color ...',...
'HandleVisibility','off',...
'Tag','scribe:legend:edgecolor');

h25 = uimenu(...
'Parent',h20,...
'Callback',mat{39},...
'Label','Line Width',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth');

h26 = uimenu(...
'Parent',h25,...
'Callback',mat{40},...
'Label','0.5',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:0.5');

h27 = uimenu(...
'Parent',h25,...
'Callback',mat{41},...
'Label','1.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:1.0');

h28 = uimenu(...
'Parent',h25,...
'Callback',mat{42},...
'Label','2.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:2.0');

h29 = uimenu(...
'Parent',h25,...
'Callback',mat{43},...
'Label','3.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:3.0');

h30 = uimenu(...
'Parent',h25,...
'Callback',mat{44},...
'Label','4.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:4.0');

h31 = uimenu(...
'Parent',h25,...
'Callback',mat{45},...
'Label','5.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:5.0');

h32 = uimenu(...
'Parent',h25,...
'Callback',mat{46},...
'Label','6.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:6.0');

h33 = uimenu(...
'Parent',h25,...
'Callback',mat{47},...
'Label','7.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:7.0');

h34 = uimenu(...
'Parent',h25,...
'Callback',mat{48},...
'Label','8.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:8.0');

h35 = uimenu(...
'Parent',h25,...
'Callback',mat{49},...
'Label','9.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:9.0');

h36 = uimenu(...
'Parent',h25,...
'Callback',mat{50},...
'Label','10.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:10.0');

h37 = uimenu(...
'Parent',h25,...
'Callback',mat{51},...
'Label','11.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:11.0');

h38 = uimenu(...
'Parent',h25,...
'Callback',mat{52},...
'Label','12.0',...
'HandleVisibility','off',...
'Tag','scribe:legend:linewidth:12.0');

h39 = uimenu(...
'Parent',h20,...
'Callback',mat{53},...
'Label','Font ...',...
'HandleVisibility','off',...
'Tag','scribe:legend:font');

h40 = uimenu(...
'Parent',h20,...
'Callback',mat{54},...
'Label','Interpreter',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter');

h41 = uimenu(...
'Parent',h40,...
'Callback',mat{55},...
'Label','latex',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter:latex');

h42 = uimenu(...
'Parent',h40,...
'Callback',mat{56},...
'Label','tex',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter:tex');

h43 = uimenu(...
'Parent',h40,...
'Callback',mat{57},...
'Label','none',...
'HandleVisibility','off',...
'Tag','scribe:legend:interpreter:none');

h44 = uimenu(...
'Parent',h20,...
'Callback',mat{58},...
'Label','Location',...
'HandleVisibility','off',...
'Tag','scribe:legend:location');

h45 = uimenu(...
'Parent',h44,...
'Callback',mat{59},...
'Label','Best',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:best');

h46 = uimenu(...
'Parent',h44,...
'Callback',mat{60},...
'Label','Inside North East',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northeast');

h47 = uimenu(...
'Parent',h44,...
'Callback',mat{61},...
'Label','Outside North East',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northeastoutside');

h48 = uimenu(...
'Parent',h44,...
'Callback',mat{62},...
'Label','Inside South East',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:southeast');

h49 = uimenu(...
'Parent',h44,...
'Callback',mat{63},...
'Label','Inside North West',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northwest');

h50 = uimenu(...
'Parent',h44,...
'Callback',mat{64},...
'Label','Outside North West',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:northwestoutside');

h51 = uimenu(...
'Parent',h44,...
'Callback',mat{65},...
'Label','Inside South West',...
'HandleVisibility','off',...
'Tag','scribe:legend:location:southwest');

h52 = uimenu(...
'Parent',h20,...
'Callback',mat{66},...
'Label','Orientation',...
'HandleVisibility','off',...
'Tag','scribe:legend:orientation');

h53 = uimenu(...
'Parent',h52,...
'Callback',mat{67},...
'Label','vertical',...
'HandleVisibility','off',...
'Tag','scribe:legend:orientation:vertical');

h54 = uimenu(...
'Parent',h52,...
'Callback',mat{68},...
'Label','horizontal',...
'HandleVisibility','off',...
'Tag','scribe:legend:orientation:horizontal');

h55 = uimenu(...
'Parent',h20,...
'Callback',mat{69},...
'Label','Show Property Editor',...
'Separator','on',...
'HandleVisibility','off',...
'Tag','scribe:legend:propedit');

h56 = uimenu(...
'Parent',h20,...
'Callback',mat{70},...
'Label','Show M-Code',...
'Separator','on',...
'HandleVisibility','off',...
'Tag','scribe:legend:mcode');

handles = [ h12 ];
set(handles, 'uicontextmenu', h20);



% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end
